### Numpy Array Operations

In [2]:
import numpy as np

In [4]:
arr = np.arange(11)
print("Basic slicing is: ", arr[1:6])
print("Slicing with step is: ", arr[1:6:2])
print("Negative index is: ", arr[-6])

Basic slicing is:  [1 2 3 4 5]
Slicing with step is:  [1 3 5]
Negative index is:  5


In [5]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("Specific Element: ", arr_2d[2,2])
print("Entire row: ", arr_2d[2])
print("Entire column: ", arr_2d[:,2])

Specific Element:  9
Entire row:  [7 8 9]
Entire column:  [3 6 9]


### Sorting

In [6]:
unsorted = np.array([1, 5, 6, 8, 3, 2, 1, 8, 9])
print("Sorted array: ", np.sort(unsorted))

arr_2d_unsorted = np.array([[1, 2], [2, 3], [4, 5], [6, 7]])
print("Sorted 2D array collumn wise: ", np.sort(arr_2d_unsorted, axis = 1))
print("Sorted 2D array row wise: ", np.sort(arr_2d_unsorted, axis = 0))

Sorted array:  [1 1 2 3 5 6 8 8 9]
Sorted 2D array collumn wise:  [[1 2]
 [2 3]
 [4 5]
 [6 7]]
Sorted 2D array row wise:  [[1 2]
 [2 3]
 [4 5]
 [6 7]]


### Filter Array

In [7]:
numbers = np.arange(1,11)
even_number = numbers[numbers % 2 == 0]
print("Even numbers in array: ", even_number)

Even numbers in array:  [ 2  4  6  8 10]


### Filter with mask

In [8]:
mask = numbers > 5
print("Numbers greater than 5: ", numbers[mask])

Numbers greater than 5:  [ 6  7  8  9 10]


### Fancy indexing vs np.where

In [9]:
indices = [0, 2, 4]
print(numbers[indices])

where_result = np.where(numbers > 5)
print("NP where: ", numbers[where_result])

[1 3 5]
NP where:  [ 6  7  8  9 10]


In [10]:
condition_array = np.where(numbers > 5, numbers * 4, numbers)
print("Condition arrray: ", condition_array)
condition_array = np.where(numbers > 5, "true", "false")
print("Condition arrray: ", condition_array)

Condition arrray:  [ 1  2  3  4  5 24 28 32 36 40]
Condition arrray:  ['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']


### Adding and removing data

In [14]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

combined = np.concatenate((arr1, arr2))
print("Combined array: ", combined)

Combined array:  [1 2 3 4 5 6]


### Array Compatiblity

In [20]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6, 10])
c = np.array([7, 8, 9])

print("Compatibility shapes:", a.shape == b.shape)

Compatibility shapes: False


In [26]:
original = np.array([[1, 2], [3, 4]])
new_row = np.array([5, 6])

with_new_row = np.vstack((original, new_row))
print("Orgiginal: \n", original)
print("With new row: \n", with_new_row)

new_col = np.array([[7], [8]])
with_new_col = np.hstack((original, new_col))
print("Orgiginal: \n", original)
print("With new collumn: \n", with_new_col)

Orgiginal: 
 [[1 2]
 [3 4]]
With new row: 
 [[1 2]
 [3 4]
 [5 6]]
Orgiginal: 
 [[1 2]
 [3 4]]
With new collumn: 
 [[1 2 7]
 [3 4 8]]


In [27]:
arr = np.arange(1,6)
deleted = np.delete(arr, 3)
print("Original:", arr)
print("Deleted:", deleted)

Original: [1 2 3 4 5]
Deleted: [1 2 3 5]
