## Numpy array and basics
Learn about numpy

In [2]:
import numpy as np

## Creating array from list

In [4]:
arr_1d = np.array([1, 2, 3])
print("1D array is: ", arr_1d)

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D array is: ", arr_2d)

1D array is:  [1 2 3]
2D array is:  [[1 2 3]
 [4 5 6]]


### List vs numpy array

In [3]:
py_list = [1, 2, 3]
print("The multiplication the list is ", py_list * 2)

np_array = np.array([1, 2, 3]) # element wise multiplication
print("The array multiplication is ", np_array * 2)

import time
start = time.time()
py_list = [i *2 for i in range(100000)]
print("\n Time for py operation is: ",  time.time() - start)

import time
start = time.time()
numpy_list = np.arange(100000) * 2
print("\n Time for numpy operation is: ",  time.time() - start)


The multiplication the list is  [1, 2, 3, 1, 2, 3]
The array multiplication is  [2 4 6]

 Time for py operation is:  0.005571842193603516

 Time for numpy operation is:  0.0015861988067626953


### Creating Array from scratch

In [29]:
np_zeros = np.zeros((3, 4))
print("Zero Arrays: \n", np_zeros)

np_ones = np.ones((4, 3))
print("One Arrays: \n", np_ones)

np_constants = np.full((3, 3), 6)
print("Constant Arrays: \n", np_constants)

np_random = np.random.random((2, 2))
print("Random Arrays: \n", np_random)

np_sequence = np.arange(23, 54, 3)
print("Sequence Arrays: \n", np_sequence)

Zero Arrays: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
One Arrays: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Constant Arrays: 
 [[6 6 6]
 [6 6 6]
 [6 6 6]]
Random Arrays: 
 [[0.51849527 0.28933606]
 [0.3555742  0.74889282]]
Sequence Arrays: 
 [23 26 29 32 35 38 41 44 47 50 53]


### Vector, Matrices and Tensor

In [33]:
vector = np.array([1, 2, 3])
print("Vector: ", vector)

matrix = np.array([[1, 2, 3], 
                  [4, 5, 6]])
print("Matrix: ", matrix)

tensor = np.array([[[1, 2], [3,4]],
                  [[5, 6], [7, 8]]])
print("Tensor:", tensor)


Vector:  [1 2 3]
Matrix:  [[1 2 3]
 [4 5 6]]
Tensor: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array Properties

In [35]:
np_array = np.array([[1, 2, 3], 
                     [4, 5, 6]])
print("Shape: ", np_array.shape)
print("Dimension: ", np_array.ndim)
print("Size: ", np_array.size)
print("Datatype: ", np_array.dtype)

Shape:  (2, 3)
Dimension:  2
Size:  6
Datatype:  int64


### Array Reshaping

In [43]:
original = np.arange(12)
print("Original array: ", original)

reshaped = original.reshape((3, 4))
print("\n Reshaped array: \n", reshaped)

flattened = reshaped.flatten()
print("\n Flattened array: \n", flattened)

# Ravel (returns new, instead of copy)
raveled = flattened.ravel()
print("\n Raveled array: \n", raveled)

transpose = reshaped.T
print("\n Transpose of array: \n", transpose)

Original array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped array: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Raveled array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transpose of array: 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
